# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/awbrenn/Documents/workspace/fluid2D/sph-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/awbrenn/Documents/workspace/fluid2D/sph-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/awbrenn/Documents/workspace/fluid2D/sph-game/CMakeFiles /home/awbrenn/Documents/workspace/fluid2D/sph-game/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/awbrenn/Documents/workspace/fluid2D/sph-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sph_particle

# Build rule for target.
sph_particle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sph_particle
.PHONY : sph_particle

# fast build rule for target.
sph_particle/fast:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/build
.PHONY : sph_particle/fast

SPHForce.o: SPHForce.cpp.o
.PHONY : SPHForce.o

# target to build an object file
SPHForce.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHForce.cpp.o
.PHONY : SPHForce.cpp.o

SPHForce.i: SPHForce.cpp.i
.PHONY : SPHForce.i

# target to preprocess a source file
SPHForce.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHForce.cpp.i
.PHONY : SPHForce.cpp.i

SPHForce.s: SPHForce.cpp.s
.PHONY : SPHForce.s

# target to generate assembly for a file
SPHForce.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHForce.cpp.s
.PHONY : SPHForce.cpp.s

SPHOccupancyVolume.o: SPHOccupancyVolume.cpp.o
.PHONY : SPHOccupancyVolume.o

# target to build an object file
SPHOccupancyVolume.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHOccupancyVolume.cpp.o
.PHONY : SPHOccupancyVolume.cpp.o

SPHOccupancyVolume.i: SPHOccupancyVolume.cpp.i
.PHONY : SPHOccupancyVolume.i

# target to preprocess a source file
SPHOccupancyVolume.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHOccupancyVolume.cpp.i
.PHONY : SPHOccupancyVolume.cpp.i

SPHOccupancyVolume.s: SPHOccupancyVolume.cpp.s
.PHONY : SPHOccupancyVolume.s

# target to generate assembly for a file
SPHOccupancyVolume.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHOccupancyVolume.cpp.s
.PHONY : SPHOccupancyVolume.cpp.s

SPHParticle.o: SPHParticle.cpp.o
.PHONY : SPHParticle.o

# target to build an object file
SPHParticle.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHParticle.cpp.o
.PHONY : SPHParticle.cpp.o

SPHParticle.i: SPHParticle.cpp.i
.PHONY : SPHParticle.i

# target to preprocess a source file
SPHParticle.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHParticle.cpp.i
.PHONY : SPHParticle.cpp.i

SPHParticle.s: SPHParticle.cpp.s
.PHONY : SPHParticle.s

# target to generate assembly for a file
SPHParticle.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHParticle.cpp.s
.PHONY : SPHParticle.cpp.s

SPHSolver.o: SPHSolver.cpp.o
.PHONY : SPHSolver.o

# target to build an object file
SPHSolver.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHSolver.cpp.o
.PHONY : SPHSolver.cpp.o

SPHSolver.i: SPHSolver.cpp.i
.PHONY : SPHSolver.i

# target to preprocess a source file
SPHSolver.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHSolver.cpp.i
.PHONY : SPHSolver.cpp.i

SPHSolver.s: SPHSolver.cpp.s
.PHONY : SPHSolver.s

# target to generate assembly for a file
SPHSolver.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/SPHSolver.cpp.s
.PHONY : SPHSolver.cpp.s

gameController.o: gameController.cpp.o
.PHONY : gameController.o

# target to build an object file
gameController.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/gameController.cpp.o
.PHONY : gameController.cpp.o

gameController.i: gameController.cpp.i
.PHONY : gameController.i

# target to preprocess a source file
gameController.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/gameController.cpp.i
.PHONY : gameController.cpp.i

gameController.s: gameController.cpp.s
.PHONY : gameController.s

# target to generate assembly for a file
gameController.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/gameController.cpp.s
.PHONY : gameController.cpp.s

gameLevel.o: gameLevel.cpp.o
.PHONY : gameLevel.o

# target to build an object file
gameLevel.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/gameLevel.cpp.o
.PHONY : gameLevel.cpp.o

gameLevel.i: gameLevel.cpp.i
.PHONY : gameLevel.i

# target to preprocess a source file
gameLevel.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/gameLevel.cpp.i
.PHONY : gameLevel.cpp.i

gameLevel.s: gameLevel.cpp.s
.PHONY : gameLevel.s

# target to generate assembly for a file
gameLevel.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/gameLevel.cpp.s
.PHONY : gameLevel.cpp.s

main_game.o: main_game.cpp.o
.PHONY : main_game.o

# target to build an object file
main_game.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/main_game.cpp.o
.PHONY : main_game.cpp.o

main_game.i: main_game.cpp.i
.PHONY : main_game.i

# target to preprocess a source file
main_game.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/main_game.cpp.i
.PHONY : main_game.cpp.i

main_game.s: main_game.cpp.s
.PHONY : main_game.s

# target to generate assembly for a file
main_game.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/main_game.cpp.s
.PHONY : main_game.cpp.s

textScreen.o: textScreen.cpp.o
.PHONY : textScreen.o

# target to build an object file
textScreen.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/textScreen.cpp.o
.PHONY : textScreen.cpp.o

textScreen.i: textScreen.cpp.i
.PHONY : textScreen.i

# target to preprocess a source file
textScreen.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/textScreen.cpp.i
.PHONY : textScreen.cpp.i

textScreen.s: textScreen.cpp.s
.PHONY : textScreen.s

# target to generate assembly for a file
textScreen.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/textScreen.cpp.s
.PHONY : textScreen.cpp.s

vector2.o: vector2.cpp.o
.PHONY : vector2.o

# target to build an object file
vector2.cpp.o:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/vector2.cpp.o
.PHONY : vector2.cpp.o

vector2.i: vector2.cpp.i
.PHONY : vector2.i

# target to preprocess a source file
vector2.cpp.i:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/vector2.cpp.i
.PHONY : vector2.cpp.i

vector2.s: vector2.cpp.s
.PHONY : vector2.s

# target to generate assembly for a file
vector2.cpp.s:
	$(MAKE) -f CMakeFiles/sph_particle.dir/build.make CMakeFiles/sph_particle.dir/vector2.cpp.s
.PHONY : vector2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sph_particle"
	@echo "... SPHForce.o"
	@echo "... SPHForce.i"
	@echo "... SPHForce.s"
	@echo "... SPHOccupancyVolume.o"
	@echo "... SPHOccupancyVolume.i"
	@echo "... SPHOccupancyVolume.s"
	@echo "... SPHParticle.o"
	@echo "... SPHParticle.i"
	@echo "... SPHParticle.s"
	@echo "... SPHSolver.o"
	@echo "... SPHSolver.i"
	@echo "... SPHSolver.s"
	@echo "... gameController.o"
	@echo "... gameController.i"
	@echo "... gameController.s"
	@echo "... gameLevel.o"
	@echo "... gameLevel.i"
	@echo "... gameLevel.s"
	@echo "... main_game.o"
	@echo "... main_game.i"
	@echo "... main_game.s"
	@echo "... textScreen.o"
	@echo "... textScreen.i"
	@echo "... textScreen.s"
	@echo "... vector2.o"
	@echo "... vector2.i"
	@echo "... vector2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

